server:
  port: 8080
  servlet:
    context-path: /jpa
spring:
  datasource:
    password: root
    url: jdbc:mysql://42.192.38.179:3306/jpa?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect